name: Secure Workflow

on: [push]

jobs:
  secure-job:
    runs-on: ubuntu-latest
    steps:
      - name: Access Secret
        run: echo "Using a secret"
        env:
          PASSWORD: ${{ secrets.MY_SECRET_PASSWORD }}
