name: Dynamic Mask Password Example

on: [push]

jobs:
  generate-mask-password:
    runs-on: ubuntu-latest
    steps:
      - name: Generate, Mask, and Store Password in Env
        run: |
          PASSWORD=$(openssl rand -base64 12)  # Generate a random password
          echo "::add-mask::$PASSWORD"  # Mask the password in logs
          echo "PASSWORD=$PASSWORD" >> $GITHUB_ENV  # Store it as an environment variable
          echo "Generated password is masked and stored in env"
